# Generated by Django 5.1.7 on 2025-08-06 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_update_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fanat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanat', to=settings.AUTH_USER_MODEL)),
                ('kumir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kumir', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
