# Generated by Django 5.1.7 on 2025-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_story_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
        migrations.RemoveField(
            model_name='story',
            name='videos',
        ),
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='media',
            field=models.FileField(default=1, upload_to='stories/'),
            preserve_default=False,
        ),
    ]
